
=== Ant-Man

di Peyton Reed

Action, Adventure, Comedy

(2015) USA

Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.

=== Big Hero 6

di Don Hall, Chris Williams

Animation, Action, Adventure

(2014) USA

The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.

=== Charlie's Angels

di McG

Action, Adventure, Comedy

(2000) USA, Germany

Three women, detectives with a mysterious boss, retrieve stolen voice-ID software, using martial arts, tech skills, and sex appeal.

=== Close Encounters of the Third Kind

di Steven Spielberg

Drama, Sci-Fi

(1977) USA

After an encounter with U.F.O.s, a line worker feels undeniably drawn to an isolated area in the wilderness where something spectacular is about to happen.

=== Dune

di David Lynch

Action, Adventure, Sci-Fi

(1984) USA

A Duke's son leads desert warriors against the galactic emperor and his father's evil nemesis when they assassinate his father and free their desert world from the emperor's rule.

=== The Fifth Element

di Luc Besson

Action, Adventure, Sci-Fi

(1997) France

In the colorful future, a cab driver unwittingly becomes the central figure in the search for a legendary cosmic weapon to keep Evil and Mr Zorg at bay.

=== Frankenstein

di James Whale

Drama, Horror, Sci-Fi

(1931) USA

An obsessed scientist assembles a living being from parts of exhumed corpses.

=== Gandhi

di Richard Attenborough

Biography, Drama, History

(1982) UK, India, USA

Gandhi's character is fully explained as a man of nonviolence. Through his patience, he is able to drive the British out of the subcontinent. And the stubborn nature of Jinnah and his commitment towards Pakistan is portrayed.

=== The Godfather

di Francis Ford Coppola

Crime, Drama

(1972) USA

The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.

=== Green Lantern

di Martin Campbell

Action, Adventure, Sci-Fi

(2011) USA

Reckless test pilot Hal Jordan is granted an alien ring that bestows him with otherworldly powers that inducts him into an intergalactic police force, the Green Lantern Corps.

=== Inside Out

di Pete Docter, Ronnie Del Carmen

Animation, Adventure, Comedy

(2015) USA

After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.

=== Kill Bill: Vol. 1

di Quentin Tarantino

Action, Crime, Thriller

(2003) USA

The Bride wakens from a four-year coma. The child she carried in her womb is gone. Now she must wreak vengeance on the team of assassins who betrayed her - a team she was once part of.

=== The Lord of the Rings

di Ralph Bakshi

Animation, Adventure, Fantasy

(1978) USA

The Fellowship of the Ring embark on a journey to destroy the One Ring and end Sauron's reign over Middle-earth.

=== M

di Fritz Lang

Crime, Drama, Mystery

(1931) Germany

When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.

=== Modern Times

di Charles Chaplin

Comedy, Drama, Family

(1936) USA

The Tramp struggles to live in modern industrial society with the help of a young homeless woman.

=== One Flew Over the Cuckoo's Nest

di Milos Forman

Drama

(1975) USA

A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.

=== Pixels

di Chris Columbus

Action, Comedy, Sci-Fi

(2015) USA, China, Canada

When aliens misinterpret video feeds of classic arcade games as a declaration of war, they attack the Earth in the form of the video games.

=== Rush

di Ron Howard

Action, Biography, Drama

(2013) UK, Germany, USA

The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.

=== Slumdog Millionaire

di Danny Boyle, Loveleen Tandan

Drama

(2008) UK, France, USA

A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of "Who Wants to be a Millionaire?"

=== Speed

di Jan de Bont

Action, Adventure, Crime

(1994) USA

A young police officer must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph.

=== Star Wars: The Force Awakens

di J.J. Abrams

Action, Adventure, Fantasy

(2015) USA

Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.

=== TRON

di Steven Lisberger

Action, Adventure, Sci-Fi

(1982) USA

A computer hacker is abducted into the digital world and forced to participate in gladiatorial games where his only chance of escape is with the help of a heroic security program.

=== Pink Floyd: The Wall

di Alan Parker

Animation, Drama, Fantasy

(1982) UK

A confined but troubled rock star descends into madness in the midst of his physical and social isolation from everyone.

=== 2001: A Space Odyssey

di Stanley Kubrick

Adventure, Sci-Fi

(1968) UK, USA

Humanity finds a mysterious, obviously artificial object buried beneath the Lunar surface and, with the intelligent computer H.A.L. 9000, sets off on a quest.

