
=== Back to the Future

di Robert Zemeckis

Adventure, Comedy, Sci-Fi

(1985) USA

Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.

=== King Kong

di Merian C. Cooper, Ernest B. Schoedsack

Adventure, Horror, Sci-Fi

(1933) USA

A film crew goes to a tropical island for an exotic location shoot and discovers a colossal ape who takes a shine to their female blonde star. He is then captured and brought back to New York City for public exhibition.

=== Star Trek: The Motion Picture

di Robert Wise

Adventure, Mystery, Sci-Fi

(1979) USA

When an alien spacecraft of enormous power is spotted approaching Earth, Admiral Kirk resumes command of the Starship Enterprise in order to intercept, examine and hopefully stop the intruder.

=== V for Vendetta

di James McTeigue

Action, Drama, Sci-Fi

(2005) USA, UK, Germany

In a future British tyranny, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow it with the help of a young woman.

