
=== The Deer Hunter

di Michael Cimino

Drama, War

(1978) USA

An in-depth examination of the ways in which the U.S. Vietnam War impacts and disrupts the lives of people in a small industrial town in Pennsylvania.

=== Frozen

di Chris Buck, Jennifer Lee

Animation, Adventure, Comedy

(2013) USA

When the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter, her sister, Anna, teams up with a mountain man, his playful reindeer, and a snowman to change the weather condition.

=== Alice in Wonderland

di Clyde Geronimi, Wilfred Jackson, Hamilton Luske

Animation, Adventure, Family

(1951) USA

Alice stumbles into the world of Wonderland. Will she get home? Not if the Queen of Hearts has her way.

=== Minions

di Kyle Balda, Pierre Coffin

Animation, Action, Adventure

(2015) USA

Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.

=== Star Wars: Episode IV - A New Hope

di George Lucas

Action, Adventure, Fantasy

(1977) USA

Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.

=== Cars

di John Lasseter, Joe Ranft

Animation, Adventure, Comedy

(2006) USA

A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.

=== Reservoir Dogs

di Quentin Tarantino

Crime, Drama, Thriller

(1992) USA

After a simple jewelry heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.

=== Iron Man

di Jon Favreau

Action, Adventure, Sci-Fi

(2008) USA

After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.

=== The Social Network

di David Fincher

Biography, Drama

(2010) USA

Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, but is later sued by two brothers who claimed he stole their idea, and the co-founder who was later squeezed out of the business.

=== Fifty Shades of Grey

di Sam Taylor-Johnson

Drama, Romance, Thriller

(2015) USA

Literature student Anastasia Steele's life changes forever when she meets handsome, yet tormented, billionaire Christian Grey.

=== The Peanuts Movie

di Steve Martino

Animation, Adventure, Comedy

(2015) USA

Snoopy embarks upon his greatest mission as he and his team take to the skies to pursue their arch-nemesis, while his best pal Charlie Brown begins his own epic quest back home to win the love of his life.

=== Blood Diamond

di Edward Zwick

Adventure, Drama, Thriller

(2006) Germany, USA

A fisherman, a smuggler, and a syndicate of businessmen match wits over the possession of a priceless diamond.

=== 101 Dalmatians

di Clyde Geronimi, Hamilton Luske, Wolfgang Reitherman

Animation, Adventure, Comedy

(1961) USA

When a litter of Dalmatian puppies are abducted by the minions of Cruella de Vil, the parents must find them before she uses them for a diabolical fashion statement.

=== Coraline

di Henry Selick

Animation, Family, Fantasy

(2009) USA

An adventurous girl finds another world that is a strangely idealized version of her frustrating home, but it has sinister secrets.

=== Spirited Away

di Hayao Miyazaki

Animation, Adventure, Family

(2001) Japan

During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.

=== Deep Red

di Dario Argento

Horror, Mystery, Thriller

(1975) Italy

After witnessing the murder of a famous psychic, a musician teams up with a feisty reporter to find the killer while evading attempts on their lives by the unseen assailant bent on keeping a dark secret buried.

=== Finding Nemo

di Andrew Stanton, Lee Unkrich

Animation, Adventure, Comedy

(2003) USA

After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.

=== Predator

di John McTiernan

Action, Sci-Fi, Thriller

(1987) USA

A team of commandos on a mission in a Central American jungle find themselves hunted by an extraterrestrial warrior.

=== Harry Potter and the Deathly Hallows: Part 1

di David Yates

Adventure, Family, Fantasy

(2010) UK, USA

As Harry races against time and evil to destroy the Horcruxes, he uncovers the existence of three most powerful objects in the wizarding world: the Deathly Hallows.

=== Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb

di Stanley Kubrick

Comedy

(1964) USA, UK

An insane general triggers a path to nuclear holocaust that a war room full of politicians and generals frantically try to stop.

=== Cat's Eye

di Lewis Teague

Comedy, Horror, Thriller

(1985) USA

A stray cat is the linking element of three tales of suspense and horror.

=== Love Story

di Arthur Hiller

Drama, Romance

(1970) USA

A boy and a girl from different backgrounds fall in love regardless of their upbringing - and then tragedy strikes.

=== WarGames

di John Badham

Sci-Fi, Thriller

(1983) USA

A young man finds a back door into a military central computer in which reality is confused with game-playing, possibly starting World War III.

=== Pretty Woman

di Garry Marshall

Comedy, Romance

(1990) USA

A man in a legal but hurtful business needs an escort for some social events, and hires a beautiful prostitute he meets... only to fall in love.

