
=== Bee Movie

di Steve Hickner, Simon J. Smith

Animation, Adventure, Comedy

(2007) USA, Australia

Barry B. Benson, a bee just graduated from college, is disillusioned at his lone career choice: making honey. On a special trip outside the hive, Barry's life is saved by Vanessa, a florist in New York City. As their relationship blossoms, he discovers humans actually eat honey, and subsequently decides to sue them.

=== Jaws

di Steven Spielberg

Adventure, Drama, Thriller

(1975) USA

A giant great white shark arrives on the shores of a New England beach resort and wreaks havoc with bloody attacks on swimmers, until a part-time sheriff teams up with a marine biologist and an old seafarer to hunt the monster down.

=== Chicken Run

di Peter Lord, Nick Park

Animation, Adventure, Comedy

(2000) UK, USA, France

When a cockerel apparently flies into a chicken farm, the chickens see him as an opportunity to escape their evil owners.

=== Pulp Fiction

di Quentin Tarantino

Crime, Drama

(1994) USA

The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.

=== A Fistful of Dollars

di Sergio Leone

Western

(1964) Italy, Spain, West Germany

A wandering gunfighter plays two rival families against each other in a town torn apart by greed, pride, and revenge.

=== Good Will Hunting

di Gus Van Sant

Drama

(1997) USA

Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.

=== The Pianist

di Roman Polanski

Biography, Drama, War

(2002) France, Poland, Germany, UK

A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.

=== Gattaca

di Andrew Niccol

Drama, Sci-Fi, Thriller

(1997) USA

A genetically inferior man assumes the identity of a superior one in order to pursue his lifelong dream of space travel.

=== From Dusk Till Dawn

di Robert Rodriguez

Action, Crime, Horror

(1996) USA

Two criminals and their hostages unknowingly seek temporary refuge in an establishment populated by vampires, with chaotic results.

=== Vertigo

di Alfred Hitchcock

Mystery, Romance, Thriller

(1958) USA

A San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.

=== The Love Bug

di Robert Stevenson

Comedy, Family, Sport

(1968) USA

A race car driver becomes a champion with a Volkswagen Beetle with a mind of its own.

=== Memento

di Christopher Nolan

Mystery, Thriller

(2000) USA

A man juggles searching for his wife's murderer and keeping his short-term memory loss from being an obstacle.

=== Labyrinth

di Jim Henson

Adventure, Family, Fantasy

(1986) UK, USA

A 16-year old girl is given 13 hours to solve a labyrinth and rescue her baby brother when her wish for him to be taken away is granted by the Goblin King.

=== Captain America: The First Avenger

di Joe Johnston

Action, Adventure, Sci-Fi

(2011) USA

Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a "Super-Soldier serum". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.

=== Il Sorpasso

di Dino Risi

Comedy, Drama

(1962) Italy

An impulsive braggart takes a shy law student for a two-day ride through the Roman and Tuscany countries.

=== The Fast and the Furious

di Rob Cohen

Action, Crime, Thriller

(2001) USA, Germany

Los Angeles police officer Brian O'Connor must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to destroy.

=== Speed Racer

di Lana Wachowski, Lilly Wachowski

Action, Family, Sci-Fi

(2008) USA, Australia, Germany

A young driver, Speed Racer, aspires to be champion of the racing world with the help of his family and his high-tech Mach 5 automobile.

=== The Dukes of Hazzard

di Jay Chandrasekhar

Action, Adventure, Comedy

(2005) USA

Cousins Bo, Luke, and Daisy Duke, and their uncle Jesse, egg on the authorities of Hazzard County, Boss Hogg and Sheriff Coltrane.

=== Six Days Seven Nights

di Ivan Reitman

Action, Adventure, Comedy

(1998) USA

Robin Monroe, a New York magazine editor, and the gruff pilot Quinn Harris must put aside their mutual dislike if they are to survive after crash landing on a deserted South Seas island.

=== Batman

di Tim Burton

Action, Adventure

(1989) USA, UK

The Dark Knight of Gotham City begins his war on crime with his first major enemy being the clownishly homicidal Joker.

=== Alien

di Ridley Scott

Horror, Sci-Fi

(1979) UK, USA

After a space merchant vessel perceives an unknown transmission as distress call, their landing on the source moon finds one of the crew attacked by a mysterious life-form, and soon realize that its life cycle has merely begun.

=== Monsters, Inc.

di Pete Docter, David Silverman, Lee Unkrich

Animation, Adventure, Comedy

(2001) USA

In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, 2 monsters realize things may not be what they think.

=== The Thin Red Line

di Terrence Malick

Drama, War

(1998) USA

Terrence Malick's adaptation of James Jones' autobiographical 1962 novel, focusing on the conflict at Guadalcanal during the second World War.

=== Creed

di Ryan Coogler

Drama, Sport

(2015) USA

The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.

