
=== The Birds

di Alfred Hitchcock

Drama, Horror, Mystery

(1963) USA

A wealthy San Francisco socialite pursues a potential boyfriend to a small Northern California town that slowly takes a turn for the bizarre when birds of all kinds suddenly begin to attack people.

=== Men in Black

di Barry Sonnenfeld

Adventure, Comedy, Family

(1997) USA

A police officer joins a secret organization that polices and monitors extraterrestrial interactions on Earth.

=== My Neighbor Totoro

di Hayao Miyazaki

Animation, Family, Fantasy

(1988) Japan

When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.

=== Entrapment

di Jon Amiel

Action, Crime, Romance

(1999) USA, UK, Germany

An insurance agent is sent by her employer to track down and help capture an art thief.

=== The Little Prince

di Mark Osborne

Animation, Adventure, Drama

(2015) France

A little girl lives in a very grown-up world with her mother, who tries to prepare her for it. Her neighbor, the Aviator, introduces the girl to an extraordinary world where anything is possible, the world of the Little Prince.

=== E.T. the Extra-Terrestrial

di Steven Spielberg

Family, Sci-Fi

(1982) USA

A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.

=== The Black Hole

di Gary Nelson

Action, Sci-Fi

(1979) USA

A research vessel finds a missing ship, commanded by a mysterious scientist, on the edge of a black hole.

=== The Ninth Gate

di Roman Polanski

Mystery, Thriller

(1999) Spain, France, USA

A rare book dealer, while seeking out the last two copies of a demon text, gets drawn into a conspiracy with supernatural overtones.

=== Spider-Man

di Sam Raimi

Action, Adventure

(2002) USA

When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.

=== American Beauty

di Sam Mendes

Drama, Romance

(1999) USA

A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.

=== Zorro

di Duccio Tessari

Action, Adventure, Comedy

(1975) Italy, France

In the New World, a new Spanish governor finds the province of Nueva Aragón under the iron fist of the corrupt Colonel Huerta and vows to bring justice under the guise of a masked avenger.

=== Titanic

di James Cameron

Drama, Romance

(1997) USA

A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.

=== Wonder Woman

di Patty Jenkins

Action, Adventure, Fantasy

(2017) USA

An Amazon princess leaves her island home to explore the world and, in doing so, becomes one of the world's greatest heroes.

=== Stargate

di Roland Emmerich

Action, Adventure, Sci-Fi

(1994) France, USA

An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.

=== The Iron Giant

di Brad Bird

Animation, Action, Adventure

(1999) USA

A young boy befriends a giant robot from outer space that a paranoid government agent wants to destroy.

=== The A-Team

di Joe Carnahan

Action, Adventure, Comedy

(2010) USA

A group of Iraq War veterans looks to clear their name with the U.S. military, who suspect the four men of committing a crime for which they were framed.

=== Signs

di M. Night Shyamalan

Drama, Mystery, Sci-Fi

(2002) USA

A family living on a farm finds mysterious crop circles in their fields which suggests something more frightening to come.

=== The Shining

di Stanley Kubrick

Drama, Horror

(1980) UK, USA

A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.

=== Escape from New York

di John Carpenter

Action, Sci-Fi

(1981) UK, USA

In 1997, when the U.S. president crashes into Manhattan, now a giant maximum security prison, a convicted bank robber is sent in to rescue him.

=== Psycho

di Alfred Hitchcock

Horror, Mystery, Thriller

(1960) USA

A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.

=== The Day the Earth Stood Still

di Robert Wise

Drama, Sci-Fi

(1951) USA

An alien lands and tells the people of Earth that they must live peacefully or be destroyed as a danger to other planets.

=== Suicide Squad

di David Ayer

Action, Adventure, Fantasy

(2016) USA

A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.

=== Thor

di Kenneth Branagh

Action, Adventure, Fantasy

(2011) USA

The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.

=== Ice Age

di Chris Wedge, Carlos Saldanha

Animation, Adventure, Comedy

(2002) USA

Set during the Ice Age, a sabertooth tiger, a sloth, and a wooly mammoth find a lost human infant, and they try to return him to his tribe.

