
=== Avatar

di James Cameron

Action, Adventure, Fantasy, Sci-Fi

(2009) USA

A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.

=== Wreck-It Ralph

di Rich Moore

Animation, Adventure, Comedy, Family, Fantasy

(2012) USA

A video game villain wants to be a hero and sets out to fulfill his dream, but his quest brings havoc to the whole arcade where he lives.

=== Blade Runner

di Ridley Scott

Action, Sci-Fi, Thriller

(1982) USA

A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.

=== Moana

di Ron Clements, John Musker, Don Hall(co-director), Chris Williams(co-director)

Animation, Adventure, Comedy

(2016) USA

In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call to seek out the Demigod to set things right.

=== The Emperor's New Groove

di Mark Dindal

Animation, Adventure, Comedy

(2000) USA

Emperor Kuzco is turned into a llama by his ex-administrator Yzma, and must now regain his throne with the help of Pacha, the gentle llama herder.

=== The NeverEnding Story

di Wolfgang Petersen

Adventure, Drama, Family

(1984) West Germany, USA

A troubled boy dives into a wondrous fantasy world through the pages of a mysterious book.

=== King Kong

di Merian C. Cooper, Ernest B. Schoedsack

Adventure, Horror, Sci-Fi

(1933) USA

A film crew goes to a tropical island for an exotic location shoot and discovers a colossal ape who takes a shine to their female blonde star. He is then captured and brought back to New York City for public exhibition.

=== Ready Player One

di Steven Spielberg

Action, Adventure, Sci-Fi

(2018) USA, India

When the creator of a virtual reality world called the OASIS dies, he releases a video in which he challenges all OASIS users to find his Easter Egg, which will give the finder his fortune.

=== V for Vendetta

di James McTeigue

Action, Drama, Sci-Fi

(2005) USA, UK, Germany

In a future British tyranny, a shadowy freedom fighter, known only by the alias of "V", plots to overthrow it with the help of a young woman.

=== The Exorcist

di William Friedkin

Horror

(1973) USA

When a 12 year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.

=== Secretary

di Steven Shainberg

Comedy, Drama, Romance

(2002) USA

A young woman, recently released from a mental hospital, gets a job as a secretary to a demanding lawyer, where their employer-employee relationship turns into a sexual, sadomasochistic one.

=== Star Trek: The Motion Picture

di Robert Wise

Adventure, Mystery, Sci-Fi

(1979) USA

When an alien spacecraft of enormous power is spotted approaching Earth, Admiral Kirk resumes command of the Starship Enterprise in order to intercept, examine and hopefully stop the intruder.

=== Nosferatu

di F.W. Murnau

Fantasy, Horror

(1922) Germany

Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter's wife.

=== The Ring

di Gore Verbinski

Horror, Mystery

(2002) USA

A journalist must investigate a mysterious videotape which seems to cause the death of anyone one week to the day after they view it.

=== Singin' in the Rain

di Stanley Donen, Gene Kelly

Comedy, Musical, Romance

(1952) USA

A silent film production company and cast make a difficult transition to sound.

=== Back to the Future

di Robert Zemeckis

Adventure, Comedy, Sci-Fi

(1985) USA

Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.

=== Aquaman

di James Wan

Action, Adventure, Fantasy, Sci-Fi

(2018) Australia, USA

Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.

=== The Great Dictator

di Charles Chaplin

Comedy, Drama, War

(1940) USA

Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.

=== Poltergeist

di Tobe Hooper

Horror, Thriller

(1982) USA

A family's home is haunted by a host of demonic ghosts.

=== Black Rain

di Ridley Scott

Action, Crime, Thriller

(1989) USA

Two NYC cops arrest a Yakuza member and must escort him when he's extradited to Japan.

=== Toy Story

di John Lasseter

Animation, Adventure, Comedy, Family, Fantasy

(1995) USA

A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.

=== The Incredibles

di Brad Bird

Animation, Action, Adventure, Family

(2004) USA

A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.

