# This is a basic workflow to help you get started with Actions

name: Build Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # setup generation scripts
    - name: Generate automated content
      run: |
        cd $GITHUB_WORKSPACE
        ls -l _scripts/
        chmod +x _scripts/*.sh  
        
    # run builders script to synch automated generated content
    - name: Generate Main page
      run: |
        cd $GITHUB_WORKSPACE
        _scripts/build-main.sh

    # run builders script to synch automated generated content
    - name: Generate Movie pages
      run: |
        cd $GITHUB_WORKSPACE
        _scripts/build-pages.sh --cleanup

    # run builders script to synch automated generated content
    - name: Generate Filmography database
      run: |
        cd $GITHUB_WORKSPACE
        _scripts/build-filmography.sh
        
     # run builders script to synch automated generated content
    - name: Generate Index pages
      run: |
        cd $GITHUB_WORKSPACE
        _scripts/build-indexes.sh

    # commit changes
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: pages updated
      
